### ISSUE TITLE
vdl recurse tests have disappeared.

### ISSUE THREAD

**Issue by suharshs** [vanadium/issues#1042]
cc: @bprosnitz 

After running the intellij dead code analyzer, there was a lot of unused code in v.io/x/ref/lib/vdl/opconst/testutil_test.go.

The tests that used that code have either moved or been deleted. We should figure out what happened to them.

**Comment by bprosnitz** [comment]
I searched the repo (with git log -S) and the only occurance of these values is in this commit https://github.com/vanadium/go.ref/commit/232d6491865430b651b279d104abfa2a641d95ed/lib/vdl/opconst/testutil_test.go back in February.

This is when our code switch between repos. Since it hasn't been used since february and is only local to the package, it seems like it is safe to get rid of?

**Comment by tatatodd** [comment]
We should make sure that we have tests of self-recursive and mututally-recursive types in all of our VDL / VOM tests.  Maybe we do have these tests and they've been renamed or something; I haven't looked.

**Comment by suharshs** [comment]
obsolete
