### ISSUE TITLE
Provide a public `scratch` dir in ns.v.dev.io mounttable

### ISSUE THREAD

**Issue by aghassemi** [vanadium/issues#1051]
Currently experimental apps that need to just mount themselves somewhere don't have a good place to do so. They need to either run their own mounttable somewhere or use credentials and mount under user's personal space on ns.dev.v.io. Too much work when experimenting with stuff. 

For the time being at least, we should provide a `/ns.dev.v.io:8101/scratch` that anyone can read/write to.

@asimshankar

**Comment by asimshankar** [comment]
https://vanadium-review.googlesource.com/18906 resolves this 
(Haven't checked it in yet, but have deployed it so it is fully operational)

As noted in the CL description, this is really a free for all so there is no protection from someone mounting on "tmp" itself and hiding names underneath.

(Oh, and instead of just mentioning - in the future please just assign the issue to me/someone :) @ mentions are easier to miss than assigned bugs, plus it makes sure that these issues aren't lost in the deluge of emails)

**Comment by yyoon** [comment]
For some reason, the new "tmp" dir appears to be a service, not a mount point (from the namespace browser). Shouldn't it be a mount point instead?

**Comment by asimshankar** [comment]
It is a mountpoint - you might have caught it at a time I was experimenting with folks overwriting each other and mounting on `tmp` itself.

The end result of the CL is that:
(a) You must have a blessing rooted in `dev.v.io` to mount. It doesn't matter what it is, so both `dev.v.io:u:<email>` and `dev.v.io:o:<clientid>` prefixes work.
(b) Once you create a mountpoint, then the creator has `Admin` rights on it - so it's a "first to make it, owns it" sort of world.
