### ISSUE TITLE
io.WriteCloser version of textutil.PrefixLineWriter?

### ISSUE THREAD

**Issue by yyoon** [vanadium/issues#1065]
@asadovsky @tatatodd 

I just realized the `textutil.PrefixLineWriter` is almost the same thing as the `prefixer` I wrote for madb tool last week (see my code here: https://github.com/vanadium/go.devtools/blob/master/madb/prefixer.go). It's good to reuse the common library, so I want to use `textutil.PrefixLineWriter` instead.

The only difference I see here is that `PrefixLineWriter` is a `textutil.WriteFlusher`, whereas my version of `prefixer` is `io.WriteCloser`, which flushes the remaining buffer that contains the unterminated last line _on close_. This way, the code gets a little bit simpler when used in gosh.

Using my `prefixer`:

``` go
cmd.AddStdoutWriter(newPrefixer(device, os.Stdout))
cmd.AddStderrWriter(newPrefixer(device, os.Stderr))
cmd.Run()
```

Using the `textutil.PrefixLineWriter`:

``` go
plwOut := textutil.PrefixLineWriter(os.Stdout, fmt.Sprintf("[%v]\t", device))
plwErr := textutil.PrefixLineWriter(os.Stderr, fmt.Sprintf("[%v]\t", device))

cmd.AddStdoutWriter(gosh.NopWriteCloser(plwOut))
cmd.AddStderrWriter(gosh.NopWriteCloser(plwErr))
cmd.Run()

plwOut.Flush()
plwErr.Flush()
```

Do you think it's reasonable to make `PrefixLineWriter` also implement a `Close` function, which flushes the buffer and then closes the underlying writer?

**Comment by tatatodd** [comment]
Yeah, Adam and I have discussed this a few times.  The original version of PrefixLineWriter did exactly that - it provided a Close method, in addition to a Flush method.  And indeed it's simpler to use with gosh.

Assume we had a Close method, and we changed the API to look like this:

  func PrefixLineWriter(w io.Writer, prefix string) io.WriteCloser

Here's where we get stuck; we have a tradeoff where neither choice seems good.  If w implements io.WriteCloser, should Close call w.Close() as well?

Let's say it does.  There's an issue here, since a common case is to pass in os.Stdout or os.Stderr as w, but we don't actually want to call os.Stdout.Close().  But sometimes it does make sense to call w.Close, e.g. if w is an os.File that we've opened.  In addition it's a little weird to take an io.Writer as input, and discover dynamically that it's an io.WriteCloser; it might be surprising to the user.

Another option that we toyed with is to add textutil.FlushOnCloser, which would take a WriteFlusher, and return a WriteCloser (or perhaps WriteFlushCloser).  That would change your call to this:

  cmd.AddStdoutWriter(textutil.FlushOnCloser(plwOut))
  cmd.AddStdoutWriter(textutil.FlushOnCloser(plwErr))
  cmd.Run()

We decided not to add FlushOnCloser, since it's only saving the two Flush() calls.  We could revisit this if we think it helps.

Also note #1063 that I filed yesterday wrt naming; it's not entirely related, but if we had shorter names that might help.

**Comment by yyoon** [comment]
Okay. These all make sense to me. It sounds like I'm following the exact path that you've gone through. I do dynamically check if the writer is a `Closer` and close it, and treat stdout/stderr as special cases, which is arguably a bad design.

For now, I guess I'll create a small wrapper around the `PrefixLineWriter`, which would save a few lines of code here and there.

BTW, #1063 was the reason I found about this library in the first place :)
Thanks for your answer.
