### ISSUE TITLE
panic: namespace: At least one root is not a rooted name

### ISSUE THREAD

**Issue by jeffallen** [vanadium/issues#1079]
While playing around with the namespace command, I made a panic. Seems like it should have given me a nice error instead.

$ vanadium/release/go/bin/namespace -v23.namespace.root=/@104.155.90.4:8101 glob *
Error: : v.io/v23/verror.NoServers: namespace <rpc.Client>"".__Glob  failed to find any compatible servers: [server=/@104.155.90.4:8101: malformed endpoint: invalid version: strconv.ParseUint: parsing "104.155.90.4:8101": invalid syntax]
MacBook-Air-de-Jeff:~ jra$ vanadium/release/go/bin/namespace -v23.namespace.root=@104.155.90.4:8101 glob *
panic: namespace: At least one root is not a rooted name: [@104.155.90.4:8101]

goroutine 1 [running]:
v.io/v23.internalInit(0x2, 0x2)
    /Users/jra/vanadium/release/go/src/v.io/v23/model.go:483 +0x47b
v.io/v23.Init(0xc8200af900, 0x2)
    /Users/jra/vanadium/release/go/src/v.io/v23/init.go:17 +0x18
v.io/x/ref/lib/v23cmd.runner.Run(0x4942fc8, 0x4943818, 0xc820186780, 0xc82000a230, 0x1, 0x1, 0x0, 0x0)
    /Users/jra/vanadium/release/go/src/v.io/x/ref/lib/v23cmd/v23cmd.go:29 +0x33
v.io/x/ref/lib/v23cmd.(*runner).Run(0xc820194c50, 0xc820186780, 0xc82000a230, 0x1, 0x1, 0x0, 0x0)
    <autogenerated>:1 +0xcc
v.io/x/lib/cmdline.ParseAndRun(0x4b87b00, 0xc820186780, 0xc82000a230, 0x1, 0x1, 0x0, 0x0)
    /Users/jra/vanadium/release/go/src/v.io/x/lib/cmdline/cmdline.go:238 +0x185
v.io/x/lib/cmdline.Main(0x4b87b00)
    /Users/jra/vanadium/release/go/src/v.io/x/lib/cmdline/cmdline.go:138 +0x254
main.main()
    /Users/jra/vanadium/release/go/src/v.io/x/ref/cmd/namespace/impl.go:35 +0x97

**Comment by caprita** [comment]
The difference in failure behavior between the two cases stems from where in the execution path the error gets encountered:

in the first case, the error happens when the Glob RPC is prepared to be issued, and appears like an RPC error

in the second case, the error happens right at the beginning, when the runtime gets initialized; specifically, the namespace's New method throws an error and internalInit panics: https://cs.corp.google.com/#vanadium/release/go/src/v.io/v23/model.go&l=483

@mattr-google : is panic'ing at runtime initialization always the right choice? IIRC the reason we don't want to return an error from v23.Init is to avoid boilerplate in always checking for that error, but for example, for command-line tools, panic'ing is a poor experience.

**Comment by ghost** [comment]
Sorry for the slow response, I think my email filtering is broken.

There are three things we can do:
1. Return an error from v23.Init().  The only downside is boilerplate, as you mentioned.
2. Panic as we do now, the downside is we get an ugly stack trace.
3. Fatal log or os.Exit.  The downside is that defers in main will not be called, which has proven annoying in the past.

If we want to switch from 2 to 1 I guess that's OK.  I suppose we could also offer v23.MustInit and v23.Init...

Let's do a quick poll.

**Comment by caprita** [comment]
I vote for a separate version of Init that returns an error (along the lines of MustInit and Init in your suggestion above). It would be easy to re-wire cmd-line tools to use the 'with error' version of init, given the existence of the v23cmd package. We could achieve a similar effect in v23cmd alone (no change to v23) by catching the panic, but that seems icky.

**Comment by ghost** [comment]
Resolved by https://vanadium-review.googlesource.com/#/c/19268/
