### ISSUE TITLE
xproxyd: unknown message type: 100

### ISSUE THREAD

**Issue by jeffallen** [vanadium/issues#1086]
I started an xproxyd, registered to a mounttabled as "servers/proxy":
  vbecome -name proxy xproxyd -name servers/proxy --v23.tcp.address :8102

I talked to it via "vrpc indentify servers/proxy", and got the right answer:
  $ vrpc identify servers/proxy
  PRESENTED: mounttabled:proxy
  VALID:     [mounttabled:proxy]
  PUBLICKEY: 6d:12:d7:17:bb:dc:8a:55:40:31:cc:26:66:77:0f:ec

But the proxy says:
  E0116 03:03:25.848215   12369 proxy.go:214] reading message failed: xproxyd: unknown message type: 100.

**Comment by caprita** [comment]
The short story is that the proxy server listening on the port published as 'servers/proxy' in your example does not behave like a typical Vanadium RPC server. Instead, it's running the proxy logic, which is probably why it's not responding to a StartCall the way the client expects when it makes an RPC (with empty method name).

A better choice to inspect a xproxyd server is to use its "-mon" server, which is a regular Vanadium RPC server and is mounted at name+"-mon" -- so in your example, servers/proxy-mon. The whole purpose of the "-mon" server is to expose debugging information about the running xproxyd process.

I assigned this to @suharshs in case you'd like to get a more detailed explanation of why you're getting the specific error you see logged by xproxyd. Otherwise, please feel free to close this.

**Comment by jeffallen** [comment]
Got it. When using alpha software, I assume every error is significant, so that's why I filed this. If you guys think this error should be silenced somehow, you can reopen it.

**Comment by suharshs** [comment]
Hmm, interesting. Its actually just luck that `vrpc identify` works with the proxy.
In fact, its only because the proxy uses a similar protocol to a normal server that `vrpc identify` is working. Hurray for accidental features! :)
Here's whats happening:

The client thinks that its talking to a normal RPC Server with the following protocol:
1. Auth handshake (client, server).
2. Send RPC Request to server.

The proxy thinks that its talking to a client (that it will need to route to a server) with the following protocol:
1. Auth handshake (client, proxy).
2. Auth handshake through proxy between (client, end server).
3. RPC Request from client to server.

So, at step 1 of both protocols happen to be the same and the client (`vrpc identify`) gets a connection to the proxy, which is all it needs to spit out the blessings and public key. (BTW If `vrpc identify` tried to complete the RPC, it would fail.)

But at step 2 the protocols diverge! The proxy gets a RPC request from the Client, when it actually expects another Auth handshake initiation from the client for the end server. This is what causes the proxy to print that error message. From the proxy's point of view, the client did in fact break protocol and should print out an error.

Hope that makes sense.
