### ISSUE TITLE
Failing website tests

### ISSUE THREAD

**Issue by ankurtaly** [vanadium/issues#1118]
Websites tests have started failing as of Feb 3, 11:30AM. These include:
vanadium-website-deploy-production
vanadium-website-deploy-staging
vanadium-website-tutorials-core
vanadium-website-tutorials-external

From the console output it seems like the makefile is running into errors.
See: https://veyron.corp.google.com/jenkins/job/vanadium-website-deploy-staging/1555/console

**Comment by suharshs** [comment]
After whatever is causing the tests to fail is fixed, vanadium-website-tutorials-core will continue to fail until https://vanadium-review.googlesource.com/#/c/19499/ is submitted.

**Comment by afandria** [comment]
https://vanadium-review.googlesource.com/#/c/19522/ seems to address this.

**Comment by afandria** [comment]
@jinjingforever

**Comment by jinjingforever** [comment]
vanadium-website-deploy-production and vanadium-website-deploy-staging have been disabled because we don't need them anymore. And I think Adam is looking at the other two. The CL Alex mentioned only addressed some results comparison issues in presubmit test.

**Comment by asadovsky** [comment]
@nlacasse 
With help from Nick and others I think I've managed to fix most of the tests.
There are two remaining issues:
- https://veyron.corp.google.com/jenkins/job/vanadium-website-tutorials-external/1477/OS=darwin/console fails because `jiri` is already in `PATH` - we need to remove it from `PATH` somehow for that test
- https://veyron.corp.google.com/jenkins/job/vanadium-website-tutorials-js-node/OS=linux/1669/console and https://veyron.corp.google.com/jenkins/job/vanadium-website-tutorials-external/1477/OS=linux/console fail because tutorial code is doing `npm install`, triggering the "shebang is too long" problem in our version of `npm`

I'll see what I can do...

**Comment by jxson** [comment]
@asadovsky I think we should remove the JS content and tests since it is unsupported, we can always resurrect from history later...

**Comment by asadovsky** [comment]
https://vanadium-review.googlesource.com/#/c/19540/ fixed the npm issue before seeing @jxson's comment. I am inclined to agree that we should drop the JS stuff. I'll start a separate issue to see if others might opine.

The only remaining issue is the `PATH` one:
https://veyron.corp.google.com/jenkins/job/vanadium-website-tutorials-external/OS=darwin/1480/console
https://veyron.corp.google.com/jenkins/job/vanadium-website-tutorials-external/OS=linux/1480/console

(This one is not tied to JS - it's running the install script and Go tests the same way an external user would.)

It should be somewhat easy to fix; we simply need to configure `PATH` to exclude `jiri` when running those particular tests. I'll think about how best to do this. @nlacasse or others, let me know if you have any ideas.

**Comment by asadovsky** [comment]
Fixed the last issue in https://vanadium-review.googlesource.com/#/c/19564/
