### ISSUE TITLE
gosh: passing t.Fatalf to Shell.Opts.Fatalf gives unintuitive output

### ISSUE THREAD

**Issue by asadovsky** [vanadium/issues#1128]
The line number that gets printed is misleading (it's the place where t.Fatalf was passed, not where it's called), you don't get a stack trace, etc. We need to improve usability here somehow.

**Comment by asadovsky** [comment]
+cc @tatatodd @cosnicolaou 

So, the problem with `Fatalf` and `Logf` is that the intuitive use of these in tests, `gosh.NewShell(gosh.Opts{Fatalf: t.Fatalf, Logf: t.Logf})`, results in incorrect line numbers, which is really bad for usability.

I filed this Go issue, but I am not confident that it's fixable: https://github.com/golang/go/issues/14415

I propose that we switch the API from taking `Fatalf` and `Logf` to taking `FailNow` and `LogLevel` arguments (exact names to be discussed), with the following semantics:
- If `FailNow` is not specified, it defaults to `panic`, or perhaps to `runtime.Goexit` (https://golang.org/pkg/runtime/#Goexit). If it's overridden to `nil` after constructing a `gosh.Shell`, failures do not panic. For tests, clients would typically set `FailNow: t.FailNow` (https://golang.org/pkg/testing/#T.FailNow).
- `LogLevel` is an enum with allowed values `Info`, `Fatal`, and `Silent`, defaulting to `Info` (since gosh intends to default to usability over performance, while providing an escape hatch for performance).
  - In `Silent` mode, we log nothing.
  - In `Fatal` mode, we log the current runtime stack before calling `FailNow`, and that's it. 
  - In `Info` mode, we log everything from `Fatal`, along with that's currently logged in gosh (which isn't much), along with the complete stdout/stderr of any failed command (or perhaps just the first and last N bytes), as per #1127.

Thoughts?

**Comment by tatatodd** [comment]
One thought: when using gosh in tests, it's nicer to use t.Log (or t.Logf) since that only shows output if -v is set, or if the test fails.  Also note that implies that t.Log output is buffered by the testing framework, so when a test uses a combination of t.Log and stdout/stderr output, the output ends up in a weird order.  I think that's an even stronger argument to at least have the option of using t.Log for output.

Let's say we can't fix the golang issue you filed, so our t.Logf / t.Fatalf calls will always log the wrong PC entry.  How bad is it if we also log the correct PC entry on that same line?  As long as the wrong PC entry is always the same, this might not be bad.  I'm thinking of output that looks like this:

```
gosh.go:10 foo_test.go:123 Failure A
gosh.go:10 foo_test.go:456 Failure B
```

The "gosh.go:10" is our unavoidable PC entry from t.Log.  I'm thinking we can control exactly what it looks like, by calling extra functions as appropriate to force the PC stack entry to what we want.

**Comment by cosnicolaou** [comment]
calling panic is unfriendly since it produces so much output..... I'd
suggest capturing the calling file/line at the same time that the error is
generated. I know Todd hates wrapping errors, but the current situation is
strictly worse in my opinion.

Cheers, Cos.

**Comment by tatatodd** [comment]
I think all proposals for fixing this bug involve capturing the calling
file/line number that caused the failure.  The proposals here are just fine
tuning the details of what the API looks like.

Todd

**Comment by asadovsky** [comment]
I think your suggestion of (a) manipulating the unavoidable PC entry and (b) adding the correct PC entry to the log line is a pretty good idea if we stick with the current API. On the other hand, the unavoidable PC entry is still kinda ugly, and I worry about the brittleness of the code around producing these PC entries in log messages. (E.g. what if Go changes the hard-coded `skip` value as part of a new release?) Also, these PC entries in log messages may be confusing for non-test code, where people wouldn't expect them. Also, the minute you're testing "real" code that logs stuff (and not just gosh), you lose some of that `t.Log` benefit anyways, since "real" code typically doesn't allow users to inject `t.Log` and `t.Fatal`.

Here's a revised proposal:
1. Replace `Fatalf` and `Logf` with a `gosh.Logger` interface with methods `FailNow` and `Logf`, defaulting to a logger implementation that uses `panic` and `log.Printf` respectively; note that `*testing.T` can be passed directly
2. Add option `ContinueOnError` (default false), dictating whether `FailNow` should be called when an error occurs
3. Add option `LogLevel`, as described in my previous proposal
4. In the implementation, make it so gosh prepends a PC on calls to `Logf`, corresponding to the first non-gosh line in the stack. This could be done by ensuring that all `Logf` invocations are performed from the same stack depth, or (perhaps easier) by iteratively invoking `runtime.Caller` until we hit the first non-gosh entry in the call stack. 

Thoughts?

@cosnicolaou - note that panic behavior changes in Go 1.6: by default, panic will only print the running goroutine's stack trace.

**Comment by tatatodd** [comment]
Using my previous example, let's call the "gosh.go:10" part the bad PC entry, and the "foo_test.go:123" part the good PC entry.

The bad PC entry is added by the call to `t.Log` itself, so any solution that uses `t.Log` (to get the nice buffered-output behavior) will end up with the bad PC entry.  In non-test code, we'll never end up with the bad PC entry.  I think we want the good PC entry to be output in all cases, regardless of test or non-test.

So basically I think we need to do what I proposed wrt injecting extra functions anyways, to make the output less confusing, when `t.Log` is used.  This is consistent with your revised proposal, just a detail on the implementation.

As for the revised proposal, my main concern is with redundancy in the API.  E.g. isn't ContinueOnError=true the same as setting FailNow=nil?  Ditto for LogLevel=Silent and Logf=nil.  In general I'd prefer only a single way to do things.

I think the main thing you're trying to accomplish with LogLevel is to provide an escape hatch for better performance.  Maybe instead we can have a bool SilentChildFailures.  In general nobody will set this to true, but if you do, we don't need to buffer the child stdout/stderr.

I do like the idea of using FailNow/Logf rather than Fatalf/Logf, since it seems more clear what each thing does.  But I'm not sure it's worth it to bundle these together into a gosh.Logger interface, since it's not clear that these two operations are that related.

So perhaps a new proposal:
1. Replace Fatalf with FailNow, which defaults to panic, or doesn't fail at all if overridden to nil after NewShell.
2. Add SilentChildFailures, which defaults to false, and thus by default we capture child stdout/stderr and log it on failure.
3. Make gosh prepend the good PC entry on calls to Logf.  I'd just ensure the same stack depth, but looking for the first non-gosh entry seems fine if you'd prefer that.
4. Ensure that if t.Logf is used, we end up with a non-confusing bad PC entry, something like "gosh.go:10".

**Comment by asadovsky** [comment]
I should've clarified: the reason for my suggestion of a `Logger` to replace the individual `FailNow` and `Logf` functions was that (a) it makes test usage a bit less verbose (just pass `Logger: t`) and (b) it avoids the need for injecting extra functions: in tests, passing `t` (as `Logger`) means that the bad PC entries will point to the true locations of `t.Logf` and `t.Fatalf` invocations within the gosh implementation, which would be intuitive and somewhat instructive. (Of course, we would still add the "good PC entries", since those are what's most useful.)

Switching from `Logf` plus `Fatalf` to `Logger` is what led me to introduce `ContinueOnError` - if all you have is `Logger`, it's somewhat awkward to temporarily disable `FailNow`. I agree with your concern about redundancy, but I think this might be a case where the other benefits make up for the redundancy shortcoming.

An idea, though: rather than calling it `Logger`, we could call it `T` - strongly suggesting that the intended use is for passing a `*testing.T`. For users wanting to temporarily disable fail-on-error, it should then be very clear that they should use `ContinueOnError`. If we want, we could make this even more explicit by not exposing the `Opts.T` on a created `Shell` - i.e. we'd copy over opts individually, and export only those that should be modifiable after creation.

A minor side benefit of this approach: my inclination is to update gosh to log the running goroutine's runtime stack before calling FailNow, as this is often quite handy for debugging. However, this would result in printing the runtime stack twice for the non-test case - once in gosh, and a second time in the panic handler. If we use the name `T`, I think it'd be reasonable to decide whether to log the runtime stack based on whether `T` is non-nil. (Alternatively, we could default to a "non-logging panic" if `T` is nil, but I don't know if such a thing exists. Maybe `runtime.Goexit()`.)

As for `LogLevel int` vs. `SilentChildFailures bool` - the latter also seems fine right now, but I worry that we'll eventually add more logging and realize that we anyways want to control the log level in a finer-grained way than a boolean. Do you see that as a concern?

**Comment by tatatodd** [comment]
Ah, I see your point that using a gosh.Logger interface avoids the "really bad PC entries"; at least they point to the actual calls to t.Logf in the gosh implementation.

Now that I'm thinking about it, I don't think my "inject extra functions" trick actually works.  The anonymous function is created when we call gosh.Opts{Logf: t.Logf}, which is always in the user's code, which is why we end up with such a confusing file/line in the first place.  And that anonymous function will always be # 3 in the PC stack, regardless of what functions we inject afterwards.  So I guess the only solution that works is to pass in *testing.T directly, as with your proposal.

There are two things I don't like about gosh.Logger.  The more important one is that the FailNow behavior seems really separate from the Logf behavior, and it's weird to bundle them together.  E.g. a non-test user that wants FailNow=panic, Logf=mylogger has to write extra stuff.  The related second point is that naming this concept seems hard.

But here's a twist; I'm not entirely convinced it's better, but it's an idea.  We can split it into two separate interfaces:

```
type Opts struct {
  // Keep the interfaces below anonymous, to avoid introducing new gosh concepts, and
  // to avoid naming these interfaces.
  FailNow interface{ FailNow() }
  Logf interface{ Logf(format string, args ...interface{}) }
}

// Here's how you create a new shell:
sh := gosh.NewShell(gosh.Opts{FailNow: t, Logf: t})
```

This way users can temporarily disable fail-on-error by setting sh.FailNow = nil, which seems reasonable.  It's still slightly more verbose then {Logger: t}, but I think it's also slightly more descriptive.

As for not printing the stack twice, I think we could just say that we only print the stack if sh.FailNow!=nil (which defaults to panic).  If the user overrides sh.FailNow to their own version that panics, they'll get 2 stacks, but that seems like a rare case anyways.

WRT LogLevel vs SilentChildFailures, my main concern is to avoid adding too many extra gosh concepts.  And the distinction between INFO and FATAL seems a bit weird, since FATAL will still output the non-fatal cleanup-related logs.  Which might lead us to introducing even more log levels.

I'd rather say that the user has no choice wrt the logging that we perform; the only thing they can do is to disable logging completely by setting sh.Logf=nil after NewShell.  And we provide sh.SilentChildFailures purely as a performance optimization, if the user wants to avoid the extra stdout/stderr buffering.

**Comment by asadovsky** [comment]
Hmm, yes, I think you're right that "inject extra functions" wouldn't work anyways.

I agree with your criticisms about `gosh.Logger`, but if we name it `gosh.T` (with comments indicating that it's meant to be used for tests) and we make it so it cannot be overridden after Shell creation (per my previous reply), I think we may be better off than with the "separate FailNow and Logf interfaces" approach.

In particular:
- To create a Shell, tests would write `gosh.NewShell(Opts{T: t, ...})`, and non-tests would write `gosh.NewShell(Opts{...})`
- To disable fail-on-error, both tests and non-tests would write `sh.ContinueOnError = true`
- Technically, both tests and non-tests could disable fail-on-error in a more complicated way by supplying a `gosh.T` with a custom `FailNow` implementation, but I don't think they would be distracted by this possibility given the name `gosh.T` and the accompanying comment describing its intended usage

With this approach, disabling logging becomes a bit more awkward, but still possible (by supplying a custom `gosh.T`). I think that's fine, because it seems like a very rare need. As for log levels: exposing a `SilentChildFailures` option (but not a `LogLevel` option) seems OK to me - I agree with your reasoning.

The "separate FailNow and Logf interfaces" approach is a little less appealing to me because for the common case of using gosh in tests, users would encounter something pretty unusual. Even if we say something like "just pass t, don't ask questions", I fear that they will find the API off-putting.

Btw: One correction to your most recent reply: if we were to have a `LogLevel` option, at level FATAL the only thing we'd log is stack traces on errors. Cleanup-related logs would only appear at level INFO.

**Comment by asadovsky** [comment]
Another quick thought: We could change the signature of `gosh.NewShell` to take only a `gosh.T`, and have clients manipulate any exposed Shell options directly on the Shell, as they currently do for Cmd. These options could get initialized to default values by `gosh.NewShell`, same as done currently. (This is made possible by https://v.io/c/19964, which eliminates the possibility of `gosh.NewShell` failing.)

**Comment by asadovsky** [comment]
@tatatodd and I discussed in person, and we'll go with my last proposal in this thread, including the changes to drop the `Opts` struct. So, we'll end up with:

```
type T interface {
  FailNow()
  Logf(format string, args ...interface{})
}

type Shell struct {
  ContinueOnError bool
  // ... other exported options, e.g. PropagateChildOutput ...
  t T // not exported
}

gosh.NewShell(t T)
```

We'll update gosh's internal error logging to include the "good PC entry" in every error message: the line of user code that invoked gosh code that resulted in the error.

As for logging command failures, we'll adopt a strategy similar to what's done in the `exec` package as of Go 1.6: we'll always log some fixed length prefix and suffix of the command's stdout and stderr (e.g. 32 kB). This lets us avoid adding options to configure logging behavior. (We may still eventually add such options if users demand it, but putting it off is nice.)

**Comment by asadovsky** [comment]
Fixed in v.io/c/20217 and co.
