### ISSUE TITLE
jiri runutil.LookPath should be replaced with (or use) v.io/x/lib/lookpath

### ISSUE THREAD

**Issue by asadovsky** [vanadium/issues#1157]
The jiri tool has its own implementation of LookPath:
https://github.com/vanadium/go.jiri/blob/master/runutil/lookpath.go

Seems we should have it use `v.io/x/lib/lookpath` instead.
(pending CL https://vanadium-review.googlesource.com/#/c/19924/)

Btw, note that some jiri code already uses the v.io/x/lib/lookpath lib, indirectly:
https://github.com/vanadium/go.jiri/blob/master/profiles/profilescmdline/manager_cmdline.go#L281

**Comment by tatatodd** [comment]
Hmm, I just realized something.

The signature for our version of LookPath is the following.  The idea is that the user passes in the PATH directories to search in, and we look for the executable with the given name.

```
func Look(dirs []string, name string) string
```

This signature makes sense for unix and plan9.  But it doesn't make sense for windows, since we also need to consult PATHEXT in order to find the allowed extensions (e.g. ".com", ".exe", etc).  For reference, see the implementation of exec.LookPath for windows:

https://golang.org/src/os/exec/lp_windows.go

We might argue that we don't support windows at the moment anyways, but it'd be nice to at least leave open the possibility of supporting it.

One way to fix the API is like this (and similar for LookPrefix):

```
func Look(vars map[string]string, name string) string
```

Here we're passing in the environment variables as a map; on unix we'll only look at PATH, but on windows we'll look at both PATH and PATHEXT.  This seems reasonable to me.  And I'll leave the windows implementation as a TODO.

But a question remains.  After this API change, should we move the lookpath logic back into envvar?  At this point it's more closely related to envvar, since we're passing in a map of envvars, and parsing PATH and PATHEXT using platform-specific rules.

**Comment by asadovsky** [comment]
Hmm, yes, that is a good point.

My inclination would be to change the signature to what you suggest, and to include a comment indicating that users may find `v.io/x/lib/envvar` useful for producing the vars map. The packages don't explicitly depend on one another, and their functionalities are somewhat divergent, so this approach keeps them separate while making it clear how `v.io/x/lib/envvar` can be helpful when using `v.io/x/lib/lookpath`. (The cost to users of both is an extra import, which doesn't seem like a big deal.)

(I could imagine using lookpath without envvar, for example, when writing linux/darwin utilities where I wish to supply PATH and nothing else.)

**Comment by tatatodd** [comment]
Fixed by https://vanadium-review.googlesource.com/#/q/topic:toddw-lib_lookpath
