### ISSUE TITLE
Jiri: combine revision and remotebranch attributes into one

### ISSUE THREAD

**Issue by shinykitten** [vanadium/issues#1161]
Jiri now checks to make sure that if revision is specified, that SHA exists on the specified remotebranch.  Considering this, in addition to the previous concept that revision should always supersede remotebranch (i.e. you sync to the SHA, not to HEAD) I propose we combine the two attributes.  The new attribute would be described as "the foo in `git checkout foo`".

**Comment by nlacasse** [comment]
cc @tatatodd

**Comment by tatatodd** [comment]
I'm in favor of this in general.  I'd just call it "revision", and when someone is using git, we'll let them set "revision" to what they normally can - i.e. a commit hash, a branch name, or a label name.

Note that in git parlance this is called "commit".  But also note that we want to leave open the possibility of supporting other revision control systems in the future, so "revision" seems more generally applicable.  This brings up the question of whether we want to keep "remotebranch" to better match other systems that actually have "full-path branches", rather than git style "single-commit branches".  My vote is to punt on those other systems, and since git uses "single-commit branches", we should just use "revision".  If we do support other systems in the future, we can decide how they should work separately.

**Comment by nlacasse** [comment]
One issue with combining remotebranch and revisions (SHAs) in a single field is that we do different things with a remotebranch vs. a SHA.

For example, when we reset the project, if we have a remotebranch we do `git reset origin/<remotebranch>`, but for SHAs we do `git reset <sha>` (no leading "origin/").

This is the first example I encountered where we treat remotebranches different that SHAs.  There may be more.

I don't really want to have to sniff the string to determine whether it's a branch, tag, or sha...

**Comment by tatatodd** [comment]
I also don't want to sniff the string to determine whether it's a branch, tag or sha.  I was hoping we'd just pass it along to git, and let git figure it all out for us.

The reset is interesting.  I would have expected that "git reset <remotebranch>" would just do what we expect.  I.e. can we just change the reset to just reset directly to whatever "revision" the user has set?

**Comment by nlacasse** [comment]
Unfortunately `git reset master` is different that `git reset origin/master`.

So if the revision is a branch name (without the leading "origin/"), we can't just pass it to reset.

We could maybe say that for branches, the revision must be `origin/<branch>`, rather than just `<branch>`, but that's kind of ugly, and I suspect we will end up stripping the leading "origin/" in some cases.

**Comment by nlacasse** [comment]
WONTFIX.
