### ISSUE TITLE
Discovery: Attachments should not have a size limit

### ISSUE THREAD

**Issue by aghassemi** [vanadium/issues#1221]
A a big size restriction like 1GB is okay but current limit is too restrictive. We should be able to support arbitrarily large attachments through RPC I assume.

**Comment by kenashcraft** [comment]
Jungho, Jeff Regan, and I discussed this in person quite a while ago.  We felt it was necessary to limit the size of attachments because if attachments get too big, you run into other problems:
- It might take a long time to fetch 1GB of data.  What behavior should Discovery have in the meantime?  Some developers will want to wait before receiving a notification, some will want it to happen in the background after receiving the notification, others will want an explicit action to fetch the data.
- What if the data is too big to fit in memory?  Does that mean that we need to stream the data to the app?  Do we need to go way out of our way not to introduce intermediate copies of the data?
- What if there is a network interruption half way through downloading 1GB of data?  Does it need to start over from the beginning?  Do we now need a more complicated resumable download API?

Our intuition is that attachments were most useful for thumbnail images where you are going to show a bunch at one time.  Anything bigger than a thumbnail and you start to run into the problems above.
