### ISSUE TITLE
VDL should required transitive exported

### ISSUE THREAD

**Issue by azinman** [vanadium/issues#1238]
There are several places where consts like Vom's WireIdBool are exported (W is uppercase), yet it's type - typeId - is not.

Swift will tell you "Property cannot be declared public because its type uses an internal type", and thus requires "transitive public."

VDL should require its exports to also be transitive, as agreed by @tatatodd.

**Comment by tatatodd** [comment]
Fixed by https://vanadium-review.googlesource.com/#/q/topic:toddw-vdl_transexport

The new rules are that T and all subtypes of T must be exported, where T is defined as...
1. All exported types T.
2. All exported consts C, with final type T after evaluation.  There is no restriction on intermediate expressions, only the type of the final value matters.
3. All interfaces I with methods M and in/out/streaming argument types T.
4. All error definitions E with argument types T.

The above group of CLs also fixes the places where we broke the above rules.  E.g. security.publicKeyDischarge, rps.unused, tunnel.unused, and vom.typeId.
