### ISSUE TITLE
Setup instructions are broken

### ISSUE THREAD

**Issue by bprosnitz** [vanadium/issues#1247]
The development setup page https://docs.google.com/document/d/1Aqm4Kx2qXCt1zNytz9QXAUlvcVLg4zN2XZTprzb0Js4/edit
links to
https://staging.v.io/community/contributing.html for setup
which links to 
https://github.com/vanadium/docs/blob/master/contributing/README.md
which is no longer existant

The installation page on vanadium.github.io:
http://vanadium.github.io/installation/
Has a script that seems to set up for tutorials - it doesn't install to JIRI_ROOT

**Comment by asadovsky** [comment]
I can't edit the doc, but I added a "suggestion" to change the link to this:
http://vanadium.github.io/community/contributing.html

**Comment by bprosnitz** [comment]
The installation instructions linked from that page are incorrect -- they set up JIRI_ROOT in a predefined location intended for the tutorials

**Comment by afandria** [comment]
Having recently setup `$JIRI_ROOT` from those instructions on some Macbook airs, I think the instructions work to setup `$JIRI_ROOT` and use the `jiri` tools. However, there's a danger that after setting up `$JIRI_ROOT` exactly that way (without copying the files over to somewhere else) that something will break. I think that either:
- re-running the tutorial script will accidentally destroy their `$JIRI_ROOT` setup and all their project branches.
- the tutorial scripts no longer work correctly for them

**Comment by jxson** [comment]
As far as I know there are two types of installations:
- Contributors
- Everyone else

Contributors should be sure to follow the link @asadovsky mentioned: http://vanadium.github.io/community/contributing.html

@bprosnitz It's not clear to me what the exact issue is with the non-contributor/tutorial installation instructions, can you elaborate? Keep in mind people using our code to run through the tutorials won't want the complexity of knowing about all the repos in $JIRI_ROOT and how they relate to each other...

**Comment by bprosnitz** [comment]
I ran the setup script yesterday on my macbook and it assumes that your
root is $HOME/v23_root and mostly ignores the JIRI_ROOT environment
variable (some packages are installed to JIRI_ROOT, most are not)

**Comment by jxson** [comment]
Hmm, okay.

Any contributors on the non-contributor install page is in the wrong place unless they are trying to run through the tutorials with a fresh install of Vanadium. I think the best corse of action is to make sure that the non-contributors install is explicitly different from core contributors setup by:
- Adding a note to the install page to direct contributors to the right place.
- The install scripts should detect a $JIRI_ROOT environment variable and maybe fail with an error message containing a link to the the contributor setup. 

Like @afandria mentioned there is a specific context for that install page and it is running the tutorials with little cognitive overhead as possible enabling integration tests for the tutorials. 

Thoughts?

**Comment by afandria** [comment]
I would agree that we should make the contributor install slightly harder to make things safer for them.

My goals are:
1. allow people to try our tutorial with the non-contributor install
2. allow users to become developers easily
3. allow contributors to run the tutorials using the installation script without destroying their own work

Note: The installation script always has `export JIRI_ROOT=${HOME}/v23_root` followed up by a rather scary `rm -rf $JIRI_ROOT` command. In other words, we definitely can't let contributors leave their code inside `$HOME/v23_root` since both of these lines prevent Goal 3 from happening.

The script is so convenient, that I prefer to leave it and change the contributing instructions. I think it's better if we pick a canonical place for $JIRI_ROOT (while also telling them that they can pick whatever they want). To differentiate it from `$HOME/v23_root`, perhaps we should pick `$HOME/Documents/vanadium_root`.
1. Installation script puts the code at `$HOME/v23_root`, temporarily setting `$JIRI_ROOT` and `$V23_RELEASE` for that shell.
2. Contributor install directs the user to move `$HOME/v23_root` to `$HOME/Documents/vanadium_root`
3. Contributor install directs the user to set `$JIRI_ROOT` to that location in their profile or bashrc.

We won't have to maintain two installation scripts this way, and my understanding is that moving the installation code somewhere else ought to be enough to satisfy these goals.

**Comment by asadovsky** [comment]
FYI: That's what we used to have, but @nlacasse and @danafergan changed it to the current state:
https://vanadium-review.googlesource.com/#/c/20715/

I agree with Alex that the "rm -rf $JIRI_ROOT" is dangerous. Why is it necessary? I.e. why can't the installation script simplify fail if $JIRI_ROOT already exists, so that developers can "rm -rf" it themselves if that's the right thing to do?

**Comment by danafergan** [comment]
That is a separate issue. At the time, if you installed through the standard script, all of the vanadium code would be at ${HOME}/v23_root , and if you installed through the step-by-step script, your JIRI_ROOT would be ${HOME}/v23_root (2nd code block at http://vanadium.github.io/installation/step-by-step.html). So it didn't make sense switching JIRI_ROOT to ${HOME}/vanadium, since there was no ${HOME}/vanadium directory.

However, I agree with @bprosnitz and @afandria 's concerns .
The real issues here are:
#1- The automated script doesn't define $JIRI_ROOT, it's only defined in step-by-step or contributor instructions. So a new user is going to have trouble if they just want to automatically install Vanadium and have everything set up.
#2- The automated script rm -rfs $JIRI_ROOT. This should be an explicit user action.

Nothing in the tutorials changes the value of $JIRI_ROOT, nor does it delete the directory.

**Comment by nlacasse** [comment]
There is no real difference between the "contributor" instructions and the "everybody else" instructions.

The contributor instructions [here](http://vanadium.github.io/community/contributing.html) point you to the usual [install instructions](http://vanadium.github.io/installation/).  The contributor instructions have extra info about the CLA and submitting CLs, but there's no difference regarding the Vanadium installation.

As @danafergan noted, the CL in v.io/c/20715 fixed an inconsistency in the contributor instructions.  If a contributor followed the install instructions as intended, they end with with a Vanadium installation in `$HOME/v23_root`, but the code block on the top of the [contributor instructions](http://vanadium.github.io/community/contributing.html) assumed the installation was in `$HOME/vanadium`, which is incorrect and confusing.

**Comment by danafergan** [comment]
@nlacasse & I just took a look. Right now, the instructions are consistent through the installation & tutorials that JIRI_ROOT should be ${HOME}/v23_root, and the tutorials don't affect the folder.

However, it's dangerous that the quick installation script at https://staging.v.io/installation/index.html wipes that folder. This is explicit on the step-by-step instructions.
Does this need to happen at all? I was able to remove that line and still complete the installation.

**Comment by jxson** [comment]
Thanks for all the info gang, I'll get a CL up shortly.

**Comment by afandria** [comment]
FYI, I just tried copying over v23_root to somewhere else, and it doesn't work directly. You will still need to modify the $JIRI_ROOT/devtools/bin symlink. Perhaps it would be better to set some environment variables to force the installation to go to the right place instead.

**Comment by nlacasse** [comment]
@afandria I'm in the process of getting rid of the devtools/bin symlink.  Users should have `$JIRI_ROOT/.jiri_root/scripts` in their PATH, not `devtools/bin`.

The website instructions have been updated as of this morning.

I'll be sending an email today about removing `devtools/bin`, and will hopefully actually remove it early next week.
