### ISSUE TITLE
Panic on first GetDeltas after Join Syncgroup

### ISSUE THREAD

**Issue by afandria** [vanadium/issues#1314]
Reproduction Steps:
- There are 3 syncbases in this scenario. A, B, and Cloud.
- A, B, and Cloud all create the same database.
- A creates a collection and creates a syncgroup referring to Cloud. (no errors)
- B waits a short duration (so that the cloud is guaranteed to be in the syncgroup) and then joins the syncgroup. (no errors)
- Shortly after, GetDeltas is performed on B, and B's syncbase crashes.

The error message is (wasn't recorded verbatim, can reproduce if necessary), but essentially it was a Go panic. `invalid memory address or nil pointer dereference`

The panic occurred on line 456 of sync_state.go, where we do `ds.sgs[sgoid].checkptGen`.

I hacked syncbase to assign `ds.sgs[sgoid]` to `&localGenInfoInMem{gen: 1}` if it happens to be nil, and the error goes away. I chose this value because several other locations in the file do the same "if nil, then set to this default value".

What I think this is:
- The new syncgroup format doesn't require that collections be created beforehand. They will be created upon joining the syncgroup.
- However, this means we have a new scenario where a joining peer's genvector has never been initialized for a collection.
- Somehow, the cloud is able to avoid this panic, perhaps because the publish step is more explicit or safe.
- It is possible that the syncgroup integration tests (in featuretests) will fail if the hierarchy creation does not include creation of the collection on every peer.

@rdvg @hpucha

**Comment by hpucha** [comment]
This crash is related to failed neighborhood advertisements. Since the advertisements fail, join doesn't finish the rest of the initialization and returns early, resulting in the crash. 

https://vanadium-review.googlesource.com/#/c/22220/ fixes the init order and should be able to handle failed advertisements with out this panic in the future. However, if the advertisements succeed, you should not run into this case.
