### ISSUE TITLE
Jenkins only +1'd one out of two CLs in a shared multi-part

### ISSUE THREAD

**Issue by azinman** [vanadium/issues#1340]
In this multipart CL:

https://vanadium-review.googlesource.com/#/c/22571
https://vanadium-review.googlesource.com/#/c/22572

They both got the same Jenkins output on May 20 4:03PM that the failed tests had now passed, but only the second CL (22572) got the +1 from Jenkins. Adam suggested this is a bug.

@jinjingforever @nlacasse

**Comment by jinjingforever** [comment]
Here is what happened:

presubmit [25113](https://veyron.corp.google.com/jenkins/job/vanadium-presubmit-test/25113/), which has the correct patchsets (22571/5, 22572/5) got aborted by @ivanpi-mtv for some reason.

Then, presubmit [25119](https://veyron.corp.google.com/jenkins/job/vanadium-presubmit-test/25119/) was manually started by @asadovsky. However, the patchsets in this one (22571/**4**, 22572/5) are not update-to-date. Even if it succeeded, it won't give +1 because the latest patchset of cl 22571 is **5**.

I see presubmit [25128](https://veyron.corp.google.com/jenkins/job/vanadium-presubmit-test/25128/) is currently running, but still with the old patchset.

Please trigger a change in either of the CLs and presubmit will pick up the latest patchsets from there.

Thanks!

**Comment by azinman** [comment]
So I rebased and submitted that. It doesn't seem to have done anything though. How to best retrigger?

**Comment by jinjingforever** [comment]
Looks like you got a +1? I see the presubmit took a longer time to run.
- Jing
