### ISSUE TITLE
www-tutorials-js-node is flaky

### ISSUE THREAD

**Issue by rogulenko** [vanadium/issues#769]
Failed several times on darwin, for example:

https://veyron.corp.google.com/jenkins/job/vanadium-www-tutorials-js-node/807/OS=darwin/

https://veyron.corp.google.com/jenkins/job/vanadium-www-tutorials-js-node/820/OS=darwin/

Please, take a look.

**Comment by afandria** [comment]
It occasionally fails on Jenkins because of chdir. A folder that it expects does not exist...

`src/fortune/ifc` should exist after doing vdl generate. However, the go build step after implies that it isn't. This also only happens occasionally and independent of the mac node number (both 1 and 2 have succeeded and failed).

**Comment by afandria** [comment]
The odd thing is that this is failing in a situation where the vanadium-www-tutorials-core should also be flaky.

@monopole

**Comment by afandria** [comment]
This seems to be okay now.
