### ISSUE TITLE
Syncbase (Mojo?) Stop Watch

### ISSUE THREAD

**Issue by afandria** [vanadium/issues#833]
I am unable to stop the watch stream with the Mojo + Dart Syncbase API. While I can stop paying attention to the stream's values, that doesn't actually close the stream.

@nlacasse

**Comment by aghassemi** [comment]
@afandria For now as a work-around, you should be able to "cancel" the stream which since we have flow-control would completely pause the flow of change events. Although it is not a cancel of the watch call, effectively it is not that different due to flow control. Although it leaves the connection open so it can be resumed later.

So one way to do this for sure is to use `stream.listen()` and then call `cancel()` on the `StreamSubscription` you get back from calling `listen`

Breaking out of a `await for` loop on the stream _May_ cancel it too depending on how Dart has implemented it. I am not sure but I will test it to see if just stopping iteration would cause the listeners to be removed and therefore cancelling the steam (I know Dart streams call cancel when the last subscriber is gone, I am hoping that's what happens here too)

**Comment by afandria** [comment]
My code breaks out of an `await for` loop, which should cancel the subscription.

However, I don't think this stops the Dart Stream. From my understanding of the (Stream API](https://api.dartlang.org/1.12.2/dart-async/Stream-class.html), Dart Streams only end when they get a 'done' message. The number of subscribers and canceled subscribers would not have an effect.

**Comment by aghassemi** [comment]
Dart sends an `onCancel` event to the `StreamContoller` when a listener ends its subscription.  ( https://api.dartlang.org/133422/dart-async/StreamController/StreamController.html ). We honor that and pause the whole flow of data in Syncbase. So if breaking out of loop actually cancels the subscription behind the scene instead of just ignoring the values coming in, then we are good. I still need to test this behavior tho, I am not sold it will. Worse case we can switch to `listen()` and call `cancel` directly.

**Comment by afandria** [comment]
Internally to my app, I have `watchEverything`, which returns a StreamSubscription and can be listened/cancelled. Since the cancel is honored by Syncbase, that should be enough.
