### ISSUE TITLE
Syncbase Feature request for RowRange to Watch

### ISSUE THREAD

**Issue by AsturaPhoenix** [vanadium/issues#852]
In some cases, it cleans up the API boundary to have per-row watches. This could be made isomorphic with scan via RowRange.

Also, let me know if this is actually an antipattern and multiple watches should actually be consolidated into a single call where possible.

**Comment by kenashcraft** [comment]
Yes, I wanted something like this for syncslides too.  @spetrovic77 and @sjamesr are signed up to implement this.

**Comment by spetrovic77** [comment]
We can definitely add a single row watch.  What behavior do you want when a
row gets deleted?  I guess that we could just terminate the watch stream.

Ross, not sure what integration you want with scan.  Can you give me an
example code?

Srdjan

**Comment by AsturaPhoenix** [comment]
Oh, I don't want any specific integration; I just meant it would be nice to reuse the RowRange data type/concept. (Though it does beg the question why watch is a database method and not a table method.)

**Comment by asadovsky** [comment]
Whatever we do, we'll want to do the same across all client libs. (To avoid slowing us down too much, maybe what we should do is maintain our Go client lib as the desired/canonical client API, but not actually keep all other client libs up-to-date with that.)

But also, I think this might be an antipattern; my inclination would be to consume a single watch stream and to propagate observed state changes to the UI from there, rather than binding individual UI components to individual watch streams. I might be off-base here, though; it may indeed be worth exploring the "individually-watched-components" approach.

It's also interesting to see the approach taken by Relay (https://facebook.github.io/react/blog/2015/02/20/introducing-relay-and-graphql.html): React components register what state they're interested in as a GraphQL query, and the Relay framework takes care of "merging" all of these queries, shipping them over to the server, and processing the results + distributing state updates to components based on their registered queries.

Unrelatedly, another limitation of the current Syncbase watch API is that it's not possible to watch a set of tables (or all tables), and also not possible to watch a query or predicate. At the very least, I think we ought to make it so one can watch all changes to a database using a single watch stream.

**Comment by asadovsky** [comment]
Closing this since we have a new issue to track it. Whoever works on the new issue can look back at this one for more information on what people were trying to do.
