### ISSUE TITLE
VIterable should throw error instead of having .error()

### ISSUE THREAD

**Issue by kenashcraft** [vanadium/issues#864]
It seems to me that the VIterable class should throw any exceptions it encounters rather than having the client check VIterable.error().  Throwing the exceptions would be more Java-y.

**Comment by spetrovic77** [comment]
We've had it this way before, and I recently changed it because it was really hard to use.

The only exception that can be thrown by an Iterable implementation is a RuntimeException.  So, the user has to write:

try {
    for (Result r : db.query()) {
       ...
    }
} catch (RuntimeException e) {
    ...
}

There are two issues here that I don't like: (1) wrapping the entire for loop, and (2) catching and handline a RuntimeException.  I think the new way is much cleaner.

**Comment by kenashcraft** [comment]
OK, WAI.
