### ISSUE TITLE
v.io/x/ref/services/xproxy/xproxy::TestMultipleProxies flaky

### ISSUE THREAD

**Issue by caprita** [vanadium/issues#868]
https://veyron.corp.google.com/jenkins/job/vanadium-go-test/1070/ARCH=amd64,OS=linux/console

@suharshs

**Comment by suharshs** [comment]
I have fixes here
https://vanadium-review.googlesource.com/#/c/17557/

and here
https://vanadium-review.googlesource.com/#/c/17558/

The second cl just removes the check for goroutines because its impossible to interrupt the net.Dial if the underlying connection breaks, which is what is happening in the test.

**Comment by suharshs** [comment]
The first cl resolve this issue.
