### ISSUE TITLE
vanadium-js-browser-integration and vanadium-js-syncbase-browser flaky

### ISSUE THREAD

**Issue by caprita** [vanadium/issues#894]
every few days it fails:
https://veyron.corp.google.com/jenkins/job/vanadium-js-syncbase-browser/1106/console
https://veyron.corp.google.com/jenkins/job/vanadium-js-syncbase-browser/1115/console

e.g.

14:35:42 go: cannot find GOROOT directory: /home/veyron/jenkins/workspace/vanadium-js-syncbase-browser/root/profiles/nacl/amd64p32_nacl/5e967194049bd1a6f097854f09fcbbbaa21afc05
14:35:42 ERROR: exit status 2
14:35:42 make[2]: Leaving directory `/home/veyron/jenkins/workspace/vanadium-js-syncbase-browser/root/release/javascript/core/extension'
14:35:42 make[2]: *** [build-test/nacl/main-64.nexe] Error 1
14:35:42 make[1]: *** [test-integration-browser-runner] Error 2
14:35:42 make[1]: Leaving directory`/home/veyron/jenkins/workspace/vanadium-js-syncbase-browser/root/release/javascript/syncbase'
14:35:42 make: **\* [test-integration-browser] Error 2
14:35:42 Make test-integration-browser:
14:35:42 exit status 2
14:35:42 
14:35:42 ##### FAILED #####

**Comment by asadovsky** [comment]
Just took a look. There appears to be some more general problem with our JS browser integration testing infrastructure, because the vanadium-js-browser-integration test has had similar failures recently. Assigning to @nlacasse who will know who's the best person to investigate this.

Example:
https://veyron.corp.google.com/jenkins/job/vanadium-js-browser-integration/1025/console

14:13:55 go: cannot find GOROOT directory: /home/veyron/jenkins/workspace/vanadium-js-browser-integration/root/profiles/nacl/amd64p32_nacl/5e967194049bd1a6f097854f09fcbbbaa21afc05
14:13:55 ERROR: exit status 2
14:13:55 make[2]: **\* [build-test/nacl/main-64.nexe] Error 1
14:13:55 make[2]: Leaving directory `/home/veyron/jenkins/workspace/vanadium-js-browser-integration/root/release/javascript/core/extension'
14:13:55 make[1]: *** [test-integration-browser-runner] Error 2
14:13:55 make[1]: Leaving directory`/home/veyron/jenkins/workspace/vanadium-js-browser-integration/root/release/javascript/core'
14:13:55 make: **\* [test-integration-browser] Error 2
14:13:55 Make test-integration-browser:
14:13:55 exit status 2
14:13:55 
14:13:55 ##### FAILED #####

**Comment by tatatodd** [comment]
Assigning to Cos, since this looks like a profile problem, and Nick is out until Wednesday.  I'll take a look too.

**Comment by caprita** [comment]
Looking at three failing instances:
https://veyron.corp.google.com/jenkins/job/vanadium-js-syncbase-browser/1115/console
https://veyron.corp.google.com/jenkins/job/vanadium-js-syncbase-browser/1106/console
https://veyron.corp.google.com/jenkins/job/vanadium-js-browser-integration/1025/console

All of them have this snippet (note the ERROR at the end):
....
19:20:13 cleanupProfiles: remove: [uninstall nacl]
19:20:13 cleanupProfiles: commands: [cleanup --ensure-specific-versions-are-set --gc]
19:20:13 jiri v23-profile list: <nil> [[
19:20:13 base =amd64-linux@1 
19:20:13 go =amd64-linux@ 
19:20:13 nacl nacl=amd64p32-nacl@2 
19:20:13 nodejs =amd64-linux@10.24 
19:20:13 syncbase =amd64-linux@ 
19:20:13 ]]
19:20:14 jiri v23-profile uninstall nacl: exit status 1 [[
19:20:14 Default target =amd64-linux@2 reinterpreted as: =amd64p32-nacl@2
19:20:14 Uninstall: nacl =amd64-linux@2: success
19:20:14 ERROR: missing version for profile go target: =amd64-linux@
...

I took a look at a few successful runs, and none of those had this ERROR message.

**Comment by cosnicolaou** [comment]
Ok, I see the problem. I'll send out a fix shortly. Basically, --ensure-specific-versions-are-set needs to run before uninstall nacl.

**Comment by caprita** [comment]
Cos submitted a fix over the weekend.
