### ISSUE TITLE
Missing GOROOT in profile

### ISSUE THREAD

**Issue by ghost** [vanadium/issues#903]
https://veyron.corp.google.com/jenkins/job/vanadium-www-tutorials-external/1008/OS=linux/console

recreate profiles with:

base amd64-linux@1 jiri v23-profile install --target=amd64-linux@1 base
nacl amd64p32-nacl@2 jiri v23-profile install --target=amd64p32-nacl@2 nacl
nodejs amd64-linux@10.24 jiri v23-profile install --target=amd64-linux@10.24 nodejs

jiri go install -x github.com/monopole/mdrip
go: cannot find GOROOT directory: /home/veyron/jenkins/workspace/vanadium-www-tutorials-external/OS/linux/root/profiles/go/amd64_linux/f2e4c8b5fb3660d793b2c545ef207153db0a34b1
ERROR: exit status 2
make: **\* [/home/veyron/jenkins/workspace/vanadium-www-tutorials-external/OS/linux/root/third_party/go/bin/mdrip] Error 1
Make test-tutorials-external:

**Comment by ghost** [comment]
Here's another:
https://veyron.corp.google.com/jenkins/job/vanadium-go-build/1118/ARCH=386,OS=linux/console

**Comment by cosnicolaou** [comment]
v.io/c/17760 fixes the (unrelated) problem with being unable to uninstall nacl when GOARCH=386 is set:
i.e. GOARCH=386 jiri v23-profile uninstall --all-targets nacl  now issues a warning rather than failing. 

The workspace in the above examples looks like a mac one where we run multiple jobs on the same machine and the single-test setup I expect to see on linux. 

The first problem you report is on node34 and it has this new structure, but it looks like someone has removed the go and syncbase profiles without removing the base one. Most likely whoever set up this new structure experimented along the way and left things in an inconsistent state.

The second example is on node23 and it has the original /home/veyron/workspace/pt directory structure. Oh and now node34 has the old structure too. In short, it looks like someone is playing with different directory structures and getting things wrong along the way... any idea who this is and why they're doing it?

**Comment by ghost** [comment]
I have no idea who might be manually messing with profiles on the jenkins machines.  Certainly I have not been doing it.

**Comment by cosnicolaou** [comment]
I have a repro.... hopefully I'll track it down tonight...

**Comment by cosnicolaou** [comment]
This has been fixed. The problem was that the tests for jiri test itself (jiri-test/internal/test) invoke internal functions that cleanup profile state. This was fixed in v.io/c/17801.
