### ISSUE TITLE
RPC stub "opts ...rpc.CallOpt" should use a different, less common variable name

### ISSUE THREAD

**Issue by asadovsky** [vanadium/issues#912]
@mattr-google @tatatodd @suharshs 

It's occasionally desirable to name an RPC argument `opts`, but this doesn't work because the VDL stub generator adds an `opts ...rpc.CallOpt` argument to every RPC method, and so there's a name collision.

Given that this builtin `opts` argument is not visible or used by developer code (either client-side or server-side), it would be nice if we could use a more obscure name for it, like `hiddenRpcFrameworkOpts` or something along these lines.

**Comment by suharshs** [comment]
Is the intention for generated code to be very human readable. If not, we can avoid collisions altogether by prefixing user defined variables with something.
But don't really mind either way 'hiddenRpcFrameworkOpts' seems fine as well.

**Comment by tatatodd** [comment]
Perhaps we could call it _opts rather than opts.  I think we use the underscore prefix for other variables to avoid collision as well.

**Comment by asadovsky** [comment]
_opts SGTM too.

**Comment by ghost** [comment]
Assigning to Todd.  This is more of a VDL thing than an RPC thing.  Todds proposal sounds totally fine to me.

**Comment by tatatodd** [comment]
I have some CLs out to fix this.  FYI instead of _opts, I chose the even better name _, which is guaranteed never to collide.  This works because the collision only occurs in our exported interfaces, where the user-provided variable names are retained for better documentation.  The actual stub implementations already ignore the user-provided variable names to avoid collisions.

You'll see what I mean when I send the CLs for review.  I just wanted to update this bug, to make it clear what the fix is.

**Comment by asadovsky** [comment]
Thanks Todd!

**Comment by tatatodd** [comment]
Fixed by https://vanadium-review.googlesource.com/#/q/topic:toddw-vdlopt
