### ISSUE TITLE
Jiri fails to call Gerrit API

### ISSUE THREAD

**Issue by pylaligand** [vanadium/issues#915]
I have a repository set up which requires the use of the SSO protocol. Jiri does not seem to be able to get the appropriate credentials in order to make Gerrit API calls, and there's no way to tell it to never make these calls (although right now I can use "jiri cl mail -set-topic=false" to prevent an error from happening).

I tried to remove the Gerrit host from my manifest, but Jiri complained about that.

**Comment by asimshankar** [comment]
@nlacasse : Could you take a look?

**Comment by nlacasse** [comment]
@pylaligand The `host` tags in jiri manifests were poorly designed since they only allowed a single gerrit host for all projects in the manifest. We got rid of the `host` tags earlier this week, and you now specify a `gerrithost` attribute each project that uses gerrit.  You can see an example of the new format here: https://vanadium.googlesource.com/manifest/+/refs/heads/master/public

I suspect your issue is due to the fact that you are using an "sso://" url for the host rather than "https://".  Is there a reason why you are doing that?

I'll add a check now that tells jiri not to talk to the Gerrit API unless the host is "https://...".

**Comment by nlacasse** [comment]
I think the correct thing to do is return an error to the user letting them know we can't set the topic if the gerrit host is not "http(s)://...".  We can tell them to either change gerrit host to "https://...", or run with `--set-topic=false`, as @pylaligand is doing.

I don't want to silently ignore the topic, since we rely on the topic for things like MultiPart CLs.

https://vanadium-review.googlesource.com/#/c/19064
