### ISSUE TITLE
Syncbase: Too many "sync: syncVClock" log messages

### ISSUE THREAD

**Issue by aghassemi** [vanadium/issues#960]
I get a lot of `sync: syncVClock: GetTime failed: syncbase_server.mojo: Internal error: no mount tables or endpoints found` in logs. Normally they are for Syncgroups that no longer exist. Could we log as warning? There are technically not errors in my case as dead syncgroups are expected for my app.

@jatinlodhia @asadovsky

**Comment by asadovsky** [comment]
These are actually due to a bug that I introduced in https://vanadium-review.googlesource.com/#/c/17806/.

This bug will be fixed in CL https://vanadium-review.googlesource.com/#/c/17960/, which is pending review from @jatinlodhia.

I'm also working on clock integration tests which would have caught this bug.

**Comment by asadovsky** [comment]
Should be fixed now. Let me know if you're still seeing this after pulling recent changes.

**Comment by aghassemi** [comment]
I still see this with latest code. Looking at the CL, clock.go still logs most things with vlog.Errorf. The one in particular that I am seeing is `syncVClock: GetTime failed`

**Comment by asadovsky** [comment]
Alex said that he stopped seeing these "GetTime failed" errors. Are you sure you're using the latest version of the Syncbase-Mojo package, 0.0.19? Can you paste in a sample from your Syncbase log?

**Comment by aghassemi** [comment]
yeah latest, I just published v20. Looking at https://github.com/vanadium/go.ref/blob/0570e063352484e2ba0f76003c44e15433a97965/services/syncbase/vsync/clock.go , the error I am seeing is logged with `vlog.Errorf`

`E1204 04:38:27.191291    8927 funcs.go:94] sync: syncVClock: GetTime failed: syncbase_server.mojo: connection to peer failed: couldn't connect to peer ccb714421324f53c []`

**Comment by asadovsky** [comment]
Discussed on chat. These errors will still get logged if sync legitimately failed (e.g. due to unavailable peer), but with the bugfix, they no longer happen when peers _can_ reach each other, which was the main problem.

As such, closing this issue.

Things will improve further once @hpucha's peer selection CLs are in, because at that point sync should rarely fail (since we'll only attempt to sync with peers that we think are available).
